# Generated by Django 6.0 on 2026-01-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortModel',
            fields=[
                ('cohort_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cohort_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CohortDefinitionModel',
            fields=[
                ('definition_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('filter_criteria', models.CharField(max_length=100)),
                ('filter_value', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('cohort_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.cohortmodel')),
            ],
        ),
    ]
