# Generated by Django 6.0 on 2026-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalGuidelineModel',
            fields=[
                ('guideline_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('guideline_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
