# Generated by Django 6.0 on 2026-01-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_departmentmodel_unitmodel_bedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='organizations.organizationmodel')),
            ],
        ),
    ]
