# Generated by Django 6.0 on 2026-01-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('patient_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('men', models.CharField(max_length=20)),
                ('ssn_encrypted', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllergyModel',
            fields=[
                ('allergy_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=30)),
                ('reaction_type', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=100)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('problem_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=30)),
                ('onset_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('icd10_code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminology.icd10codemodel')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientmodel')),
            ],
        ),
    ]
