# Generated by Django 6.0 on 2026-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCodeModel',
            fields=[
                ('code_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cpt_code', models.CharField(max_length=100)),
                ('procedure_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ICD10CodeModel',
            fields=[
                ('code_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LOINCCodeModel',
            fields=[
                ('code_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('loinc_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
