# Generated by Django 6.0 on 2026-01-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('org_id', models.CharField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=50, unique=True)),
                ('bed_count', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('npi_number', models.CharField()),
            ],
        ),
    ]
