# Generated by Django 6.0 on 2026-01-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('department_id', models.CharField(primary_key=True, serialize=False)),
                ('department_name', models.CharField()),
                ('type', models.CharField()),
                ('org_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep', to='organizations.organizationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('unit_id', models.CharField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField()),
                ('unit_type', models.CharField()),
                ('bed_count', models.IntegerField()),
                ('department_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='organizations.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BedModel',
            fields=[
                ('bed_id', models.CharField(primary_key=True, serialize=False)),
                ('bed_number', models.CharField()),
                ('status', models.CharField()),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed', to='organizations.unitmodel')),
            ],
        ),
    ]
